//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by orlop-gen. DO NOT EDIT.

package v1

import (
	"encoding/json"

	privatev1 "github.com/openshift-online/gecko/platform-api/api/private/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*privatev1.AutoscalingSpec)(nil), (*AutoscalingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_AutoscalingSpec_PrivateToPublic(a.(*privatev1.AutoscalingSpec), b.(*AutoscalingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*AutoscalingSpec)(nil), (*privatev1.AutoscalingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_AutoscalingSpec_PublicToPrivate(a.(*AutoscalingSpec), b.(*privatev1.AutoscalingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.Channel)(nil), (*Channel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Channel_PrivateToPublic(a.(*privatev1.Channel), b.(*Channel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Channel)(nil), (*privatev1.Channel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Channel_PublicToPrivate(a.(*Channel), b.(*privatev1.Channel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ChannelList)(nil), (*ChannelList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ChannelList_PrivateToPublic(a.(*privatev1.ChannelList), b.(*ChannelList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ChannelList)(nil), (*privatev1.ChannelList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ChannelList_PublicToPrivate(a.(*ChannelList), b.(*privatev1.ChannelList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ChannelSpec)(nil), (*ChannelSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ChannelSpec_PrivateToPublic(a.(*privatev1.ChannelSpec), b.(*ChannelSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ChannelSpec)(nil), (*privatev1.ChannelSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ChannelSpec_PublicToPrivate(a.(*ChannelSpec), b.(*privatev1.ChannelSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.Cluster)(nil), (*Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Cluster_PrivateToPublic(a.(*privatev1.Cluster), b.(*Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Cluster)(nil), (*privatev1.Cluster)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Cluster_PublicToPrivate(a.(*Cluster), b.(*privatev1.Cluster), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterList)(nil), (*ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterList_PrivateToPublic(a.(*privatev1.ClusterList), b.(*ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterList)(nil), (*privatev1.ClusterList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterList_PublicToPrivate(a.(*ClusterList), b.(*privatev1.ClusterList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterNetworkEntry)(nil), (*ClusterNetworkEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterNetworkEntry_PrivateToPublic(a.(*privatev1.ClusterNetworkEntry), b.(*ClusterNetworkEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterNetworkEntry)(nil), (*privatev1.ClusterNetworkEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterNetworkEntry_PublicToPrivate(a.(*ClusterNetworkEntry), b.(*privatev1.ClusterNetworkEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterPlatformSpec)(nil), (*ClusterPlatformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterPlatformSpec_PrivateToPublic(a.(*privatev1.ClusterPlatformSpec), b.(*ClusterPlatformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterPlatformSpec)(nil), (*privatev1.ClusterPlatformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterPlatformSpec_PublicToPrivate(a.(*ClusterPlatformSpec), b.(*privatev1.ClusterPlatformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterSpec)(nil), (*ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterSpec_PrivateToPublic(a.(*privatev1.ClusterSpec), b.(*ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterSpec)(nil), (*privatev1.ClusterSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterSpec_PublicToPrivate(a.(*ClusterSpec), b.(*privatev1.ClusterSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ClusterStatus)(nil), (*ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterStatus_PrivateToPublic(a.(*privatev1.ClusterStatus), b.(*ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterStatus)(nil), (*privatev1.ClusterStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ClusterStatus_PublicToPrivate(a.(*ClusterStatus), b.(*privatev1.ClusterStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ControlPlaneMaintenanceExclusion)(nil), (*ControlPlaneMaintenanceExclusion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneMaintenanceExclusion_PrivateToPublic(a.(*privatev1.ControlPlaneMaintenanceExclusion), b.(*ControlPlaneMaintenanceExclusion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneMaintenanceExclusion)(nil), (*privatev1.ControlPlaneMaintenanceExclusion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneMaintenanceExclusion_PublicToPrivate(a.(*ControlPlaneMaintenanceExclusion), b.(*privatev1.ControlPlaneMaintenanceExclusion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ControlPlaneMaintenanceRecurrence)(nil), (*ControlPlaneMaintenanceRecurrence)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneMaintenanceRecurrence_PrivateToPublic(a.(*privatev1.ControlPlaneMaintenanceRecurrence), b.(*ControlPlaneMaintenanceRecurrence), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneMaintenanceRecurrence)(nil), (*privatev1.ControlPlaneMaintenanceRecurrence)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneMaintenanceRecurrence_PublicToPrivate(a.(*ControlPlaneMaintenanceRecurrence), b.(*privatev1.ControlPlaneMaintenanceRecurrence), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ControlPlaneMaintenanceWindow)(nil), (*ControlPlaneMaintenanceWindow)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneMaintenanceWindow_PrivateToPublic(a.(*privatev1.ControlPlaneMaintenanceWindow), b.(*ControlPlaneMaintenanceWindow), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneMaintenanceWindow)(nil), (*privatev1.ControlPlaneMaintenanceWindow)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneMaintenanceWindow_PublicToPrivate(a.(*ControlPlaneMaintenanceWindow), b.(*privatev1.ControlPlaneMaintenanceWindow), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ControlPlaneUpgradePolicy)(nil), (*ControlPlaneUpgradePolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneUpgradePolicy_PrivateToPublic(a.(*privatev1.ControlPlaneUpgradePolicy), b.(*ControlPlaneUpgradePolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneUpgradePolicy)(nil), (*privatev1.ControlPlaneUpgradePolicy)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneUpgradePolicy_PublicToPrivate(a.(*ControlPlaneUpgradePolicy), b.(*privatev1.ControlPlaneUpgradePolicy), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ControlPlaneUpgradePolicyList)(nil), (*ControlPlaneUpgradePolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneUpgradePolicyList_PrivateToPublic(a.(*privatev1.ControlPlaneUpgradePolicyList), b.(*ControlPlaneUpgradePolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneUpgradePolicyList)(nil), (*privatev1.ControlPlaneUpgradePolicyList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneUpgradePolicyList_PublicToPrivate(a.(*ControlPlaneUpgradePolicyList), b.(*privatev1.ControlPlaneUpgradePolicyList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ControlPlaneUpgradePolicySpec)(nil), (*ControlPlaneUpgradePolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneUpgradePolicySpec_PrivateToPublic(a.(*privatev1.ControlPlaneUpgradePolicySpec), b.(*ControlPlaneUpgradePolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneUpgradePolicySpec)(nil), (*privatev1.ControlPlaneUpgradePolicySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneUpgradePolicySpec_PublicToPrivate(a.(*ControlPlaneUpgradePolicySpec), b.(*privatev1.ControlPlaneUpgradePolicySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ControlPlaneUpgradePolicyStatus)(nil), (*ControlPlaneUpgradePolicyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneUpgradePolicyStatus_PrivateToPublic(a.(*privatev1.ControlPlaneUpgradePolicyStatus), b.(*ControlPlaneUpgradePolicyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneUpgradePolicyStatus)(nil), (*privatev1.ControlPlaneUpgradePolicyStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ControlPlaneUpgradePolicyStatus_PublicToPrivate(a.(*ControlPlaneUpgradePolicyStatus), b.(*privatev1.ControlPlaneUpgradePolicyStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.DNSSpec)(nil), (*DNSSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_DNSSpec_PrivateToPublic(a.(*privatev1.DNSSpec), b.(*DNSSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*DNSSpec)(nil), (*privatev1.DNSSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_DNSSpec_PublicToPrivate(a.(*DNSSpec), b.(*privatev1.DNSSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.GCPClusterPlatform)(nil), (*GCPClusterPlatform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPClusterPlatform_PrivateToPublic(a.(*privatev1.GCPClusterPlatform), b.(*GCPClusterPlatform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPClusterPlatform)(nil), (*privatev1.GCPClusterPlatform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPClusterPlatform_PublicToPrivate(a.(*GCPClusterPlatform), b.(*privatev1.GCPClusterPlatform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.GCPNodePoolPlatform)(nil), (*GCPNodePoolPlatform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPNodePoolPlatform_PrivateToPublic(a.(*privatev1.GCPNodePoolPlatform), b.(*GCPNodePoolPlatform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPNodePoolPlatform)(nil), (*privatev1.GCPNodePoolPlatform)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPNodePoolPlatform_PublicToPrivate(a.(*GCPNodePoolPlatform), b.(*privatev1.GCPNodePoolPlatform), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.GCPResourceLabel)(nil), (*GCPResourceLabel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPResourceLabel_PrivateToPublic(a.(*privatev1.GCPResourceLabel), b.(*GCPResourceLabel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*GCPResourceLabel)(nil), (*privatev1.GCPResourceLabel)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_GCPResourceLabel_PublicToPrivate(a.(*GCPResourceLabel), b.(*privatev1.GCPResourceLabel), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.HostedClusterResult)(nil), (*HostedClusterResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_HostedClusterResult_PrivateToPublic(a.(*privatev1.HostedClusterResult), b.(*HostedClusterResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*HostedClusterResult)(nil), (*privatev1.HostedClusterResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_HostedClusterResult_PublicToPrivate(a.(*HostedClusterResult), b.(*privatev1.HostedClusterResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.MachineNetworkEntry)(nil), (*MachineNetworkEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_MachineNetworkEntry_PrivateToPublic(a.(*privatev1.MachineNetworkEntry), b.(*MachineNetworkEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineNetworkEntry)(nil), (*privatev1.MachineNetworkEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_MachineNetworkEntry_PublicToPrivate(a.(*MachineNetworkEntry), b.(*privatev1.MachineNetworkEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NetworkingSpec)(nil), (*NetworkingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NetworkingSpec_PrivateToPublic(a.(*privatev1.NetworkingSpec), b.(*NetworkingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkingSpec)(nil), (*privatev1.NetworkingSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NetworkingSpec_PublicToPrivate(a.(*NetworkingSpec), b.(*privatev1.NetworkingSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePool)(nil), (*NodePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePool_PrivateToPublic(a.(*privatev1.NodePool), b.(*NodePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePool)(nil), (*privatev1.NodePool)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePool_PublicToPrivate(a.(*NodePool), b.(*privatev1.NodePool), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePoolList)(nil), (*NodePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolList_PrivateToPublic(a.(*privatev1.NodePoolList), b.(*NodePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePoolList)(nil), (*privatev1.NodePoolList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolList_PublicToPrivate(a.(*NodePoolList), b.(*privatev1.NodePoolList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePoolPlatformSpec)(nil), (*NodePoolPlatformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolPlatformSpec_PrivateToPublic(a.(*privatev1.NodePoolPlatformSpec), b.(*NodePoolPlatformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePoolPlatformSpec)(nil), (*privatev1.NodePoolPlatformSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolPlatformSpec_PublicToPrivate(a.(*NodePoolPlatformSpec), b.(*privatev1.NodePoolPlatformSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePoolSpec)(nil), (*NodePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolSpec_PrivateToPublic(a.(*privatev1.NodePoolSpec), b.(*NodePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePoolSpec)(nil), (*privatev1.NodePoolSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolSpec_PublicToPrivate(a.(*NodePoolSpec), b.(*privatev1.NodePoolSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.NodePoolStatus)(nil), (*NodePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolStatus_PrivateToPublic(a.(*privatev1.NodePoolStatus), b.(*NodePoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NodePoolStatus)(nil), (*privatev1.NodePoolStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_NodePoolStatus_PublicToPrivate(a.(*NodePoolStatus), b.(*privatev1.NodePoolStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.Quota)(nil), (*Quota)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Quota_PrivateToPublic(a.(*privatev1.Quota), b.(*Quota), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Quota)(nil), (*privatev1.Quota)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Quota_PublicToPrivate(a.(*Quota), b.(*privatev1.Quota), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.QuotaList)(nil), (*QuotaList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaList_PrivateToPublic(a.(*privatev1.QuotaList), b.(*QuotaList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaList)(nil), (*privatev1.QuotaList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaList_PublicToPrivate(a.(*QuotaList), b.(*privatev1.QuotaList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.QuotaRequest)(nil), (*QuotaRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaRequest_PrivateToPublic(a.(*privatev1.QuotaRequest), b.(*QuotaRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaRequest)(nil), (*privatev1.QuotaRequest)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaRequest_PublicToPrivate(a.(*QuotaRequest), b.(*privatev1.QuotaRequest), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.QuotaRequestList)(nil), (*QuotaRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaRequestList_PrivateToPublic(a.(*privatev1.QuotaRequestList), b.(*QuotaRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaRequestList)(nil), (*privatev1.QuotaRequestList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaRequestList_PublicToPrivate(a.(*QuotaRequestList), b.(*privatev1.QuotaRequestList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.QuotaRequestSpec)(nil), (*QuotaRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaRequestSpec_PrivateToPublic(a.(*privatev1.QuotaRequestSpec), b.(*QuotaRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaRequestSpec)(nil), (*privatev1.QuotaRequestSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaRequestSpec_PublicToPrivate(a.(*QuotaRequestSpec), b.(*privatev1.QuotaRequestSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.QuotaRequestStatus)(nil), (*QuotaRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaRequestStatus_PrivateToPublic(a.(*privatev1.QuotaRequestStatus), b.(*QuotaRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaRequestStatus)(nil), (*privatev1.QuotaRequestStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaRequestStatus_PublicToPrivate(a.(*QuotaRequestStatus), b.(*privatev1.QuotaRequestStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.QuotaResourceSpec)(nil), (*QuotaResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaResourceSpec_PrivateToPublic(a.(*privatev1.QuotaResourceSpec), b.(*QuotaResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaResourceSpec)(nil), (*privatev1.QuotaResourceSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaResourceSpec_PublicToPrivate(a.(*QuotaResourceSpec), b.(*privatev1.QuotaResourceSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.QuotaResourceStatus)(nil), (*QuotaResourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaResourceStatus_PrivateToPublic(a.(*privatev1.QuotaResourceStatus), b.(*QuotaResourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaResourceStatus)(nil), (*privatev1.QuotaResourceStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaResourceStatus_PublicToPrivate(a.(*QuotaResourceStatus), b.(*privatev1.QuotaResourceStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.QuotaSpec)(nil), (*QuotaSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaSpec_PrivateToPublic(a.(*privatev1.QuotaSpec), b.(*QuotaSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaSpec)(nil), (*privatev1.QuotaSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaSpec_PublicToPrivate(a.(*QuotaSpec), b.(*privatev1.QuotaSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.QuotaStatus)(nil), (*QuotaStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaStatus_PrivateToPublic(a.(*privatev1.QuotaStatus), b.(*QuotaStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*QuotaStatus)(nil), (*privatev1.QuotaStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_QuotaStatus_PublicToPrivate(a.(*QuotaStatus), b.(*privatev1.QuotaStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ReleaseSpec)(nil), (*ReleaseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ReleaseSpec_PrivateToPublic(a.(*privatev1.ReleaseSpec), b.(*ReleaseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ReleaseSpec)(nil), (*privatev1.ReleaseSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ReleaseSpec_PublicToPrivate(a.(*ReleaseSpec), b.(*privatev1.ReleaseSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.ServiceAccountsRef)(nil), (*ServiceAccountsRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ServiceAccountsRef_PrivateToPublic(a.(*privatev1.ServiceAccountsRef), b.(*ServiceAccountsRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ServiceAccountsRef)(nil), (*privatev1.ServiceAccountsRef)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_ServiceAccountsRef_PublicToPrivate(a.(*ServiceAccountsRef), b.(*privatev1.ServiceAccountsRef), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.TaintSpec)(nil), (*TaintSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_TaintSpec_PrivateToPublic(a.(*privatev1.TaintSpec), b.(*TaintSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TaintSpec)(nil), (*privatev1.TaintSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_TaintSpec_PublicToPrivate(a.(*TaintSpec), b.(*privatev1.TaintSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.Version)(nil), (*Version)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Version_PrivateToPublic(a.(*privatev1.Version), b.(*Version), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*Version)(nil), (*privatev1.Version)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_Version_PublicToPrivate(a.(*Version), b.(*privatev1.Version), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.VersionList)(nil), (*VersionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_VersionList_PrivateToPublic(a.(*privatev1.VersionList), b.(*VersionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VersionList)(nil), (*privatev1.VersionList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_VersionList_PublicToPrivate(a.(*VersionList), b.(*privatev1.VersionList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.VersionSpec)(nil), (*VersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_VersionSpec_PrivateToPublic(a.(*privatev1.VersionSpec), b.(*VersionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*VersionSpec)(nil), (*privatev1.VersionSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_VersionSpec_PublicToPrivate(a.(*VersionSpec), b.(*privatev1.VersionSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*privatev1.WorkloadIdentitySpec)(nil), (*WorkloadIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_WorkloadIdentitySpec_PrivateToPublic(a.(*privatev1.WorkloadIdentitySpec), b.(*WorkloadIdentitySpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkloadIdentitySpec)(nil), (*privatev1.WorkloadIdentitySpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_WorkloadIdentitySpec_PublicToPrivate(a.(*WorkloadIdentitySpec), b.(*privatev1.WorkloadIdentitySpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_AutoscalingSpec_PrivateToPublic(in *privatev1.AutoscalingSpec, out *AutoscalingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_AutoscalingSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_AutoscalingSpec_PrivateToPublic(in *privatev1.AutoscalingSpec, out *AutoscalingSpec, s conversion.Scope) error {
	return autoConvert_AutoscalingSpec_PrivateToPublic(in, out, s)
}

func autoConvert_AutoscalingSpec_PublicToPrivate(in *AutoscalingSpec, out *privatev1.AutoscalingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_AutoscalingSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_AutoscalingSpec_PublicToPrivate(in *AutoscalingSpec, out *privatev1.AutoscalingSpec, s conversion.Scope) error {
	return autoConvert_AutoscalingSpec_PublicToPrivate(in, out, s)
}

func autoConvert_Channel_PrivateToPublic(in *privatev1.Channel, out *Channel, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Channel_PrivateToPublic is an autogenerated conversion function.
func Convert_Channel_PrivateToPublic(in *privatev1.Channel, out *Channel, s conversion.Scope) error {
	return autoConvert_Channel_PrivateToPublic(in, out, s)
}

func autoConvert_Channel_PublicToPrivate(in *Channel, out *privatev1.Channel, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Channel_PublicToPrivate is an autogenerated conversion function.
func Convert_Channel_PublicToPrivate(in *Channel, out *privatev1.Channel, s conversion.Scope) error {
	return autoConvert_Channel_PublicToPrivate(in, out, s)
}

func autoConvert_ChannelList_PrivateToPublic(in *privatev1.ChannelList, out *ChannelList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ChannelList_PrivateToPublic is an autogenerated conversion function.
func Convert_ChannelList_PrivateToPublic(in *privatev1.ChannelList, out *ChannelList, s conversion.Scope) error {
	return autoConvert_ChannelList_PrivateToPublic(in, out, s)
}

func autoConvert_ChannelList_PublicToPrivate(in *ChannelList, out *privatev1.ChannelList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ChannelList_PublicToPrivate is an autogenerated conversion function.
func Convert_ChannelList_PublicToPrivate(in *ChannelList, out *privatev1.ChannelList, s conversion.Scope) error {
	return autoConvert_ChannelList_PublicToPrivate(in, out, s)
}

func autoConvert_ChannelSpec_PrivateToPublic(in *privatev1.ChannelSpec, out *ChannelSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ChannelSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_ChannelSpec_PrivateToPublic(in *privatev1.ChannelSpec, out *ChannelSpec, s conversion.Scope) error {
	return autoConvert_ChannelSpec_PrivateToPublic(in, out, s)
}

func autoConvert_ChannelSpec_PublicToPrivate(in *ChannelSpec, out *privatev1.ChannelSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ChannelSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_ChannelSpec_PublicToPrivate(in *ChannelSpec, out *privatev1.ChannelSpec, s conversion.Scope) error {
	return autoConvert_ChannelSpec_PublicToPrivate(in, out, s)
}

func autoConvert_Cluster_PrivateToPublic(in *privatev1.Cluster, out *Cluster, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Cluster_PrivateToPublic is an autogenerated conversion function.
func Convert_Cluster_PrivateToPublic(in *privatev1.Cluster, out *Cluster, s conversion.Scope) error {
	return autoConvert_Cluster_PrivateToPublic(in, out, s)
}

func autoConvert_Cluster_PublicToPrivate(in *Cluster, out *privatev1.Cluster, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Cluster_PublicToPrivate is an autogenerated conversion function.
func Convert_Cluster_PublicToPrivate(in *Cluster, out *privatev1.Cluster, s conversion.Scope) error {
	return autoConvert_Cluster_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterList_PrivateToPublic(in *privatev1.ClusterList, out *ClusterList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterList_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterList_PrivateToPublic(in *privatev1.ClusterList, out *ClusterList, s conversion.Scope) error {
	return autoConvert_ClusterList_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterList_PublicToPrivate(in *ClusterList, out *privatev1.ClusterList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterList_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterList_PublicToPrivate(in *ClusterList, out *privatev1.ClusterList, s conversion.Scope) error {
	return autoConvert_ClusterList_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterNetworkEntry_PrivateToPublic(in *privatev1.ClusterNetworkEntry, out *ClusterNetworkEntry, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterNetworkEntry_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterNetworkEntry_PrivateToPublic(in *privatev1.ClusterNetworkEntry, out *ClusterNetworkEntry, s conversion.Scope) error {
	return autoConvert_ClusterNetworkEntry_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterNetworkEntry_PublicToPrivate(in *ClusterNetworkEntry, out *privatev1.ClusterNetworkEntry, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterNetworkEntry_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterNetworkEntry_PublicToPrivate(in *ClusterNetworkEntry, out *privatev1.ClusterNetworkEntry, s conversion.Scope) error {
	return autoConvert_ClusterNetworkEntry_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterPlatformSpec_PrivateToPublic(in *privatev1.ClusterPlatformSpec, out *ClusterPlatformSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterPlatformSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterPlatformSpec_PrivateToPublic(in *privatev1.ClusterPlatformSpec, out *ClusterPlatformSpec, s conversion.Scope) error {
	return autoConvert_ClusterPlatformSpec_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterPlatformSpec_PublicToPrivate(in *ClusterPlatformSpec, out *privatev1.ClusterPlatformSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterPlatformSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterPlatformSpec_PublicToPrivate(in *ClusterPlatformSpec, out *privatev1.ClusterPlatformSpec, s conversion.Scope) error {
	return autoConvert_ClusterPlatformSpec_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterSpec_PrivateToPublic(in *privatev1.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterSpec_PrivateToPublic(in *privatev1.ClusterSpec, out *ClusterSpec, s conversion.Scope) error {
	return autoConvert_ClusterSpec_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterSpec_PublicToPrivate(in *ClusterSpec, out *privatev1.ClusterSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterSpec_PublicToPrivate(in *ClusterSpec, out *privatev1.ClusterSpec, s conversion.Scope) error {
	return autoConvert_ClusterSpec_PublicToPrivate(in, out, s)
}

func autoConvert_ClusterStatus_PrivateToPublic(in *privatev1.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_ClusterStatus_PrivateToPublic(in *privatev1.ClusterStatus, out *ClusterStatus, s conversion.Scope) error {
	return autoConvert_ClusterStatus_PrivateToPublic(in, out, s)
}

func autoConvert_ClusterStatus_PublicToPrivate(in *ClusterStatus, out *privatev1.ClusterStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ClusterStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_ClusterStatus_PublicToPrivate(in *ClusterStatus, out *privatev1.ClusterStatus, s conversion.Scope) error {
	return autoConvert_ClusterStatus_PublicToPrivate(in, out, s)
}

func autoConvert_ControlPlaneMaintenanceExclusion_PrivateToPublic(in *privatev1.ControlPlaneMaintenanceExclusion, out *ControlPlaneMaintenanceExclusion, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneMaintenanceExclusion_PrivateToPublic is an autogenerated conversion function.
func Convert_ControlPlaneMaintenanceExclusion_PrivateToPublic(in *privatev1.ControlPlaneMaintenanceExclusion, out *ControlPlaneMaintenanceExclusion, s conversion.Scope) error {
	return autoConvert_ControlPlaneMaintenanceExclusion_PrivateToPublic(in, out, s)
}

func autoConvert_ControlPlaneMaintenanceExclusion_PublicToPrivate(in *ControlPlaneMaintenanceExclusion, out *privatev1.ControlPlaneMaintenanceExclusion, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneMaintenanceExclusion_PublicToPrivate is an autogenerated conversion function.
func Convert_ControlPlaneMaintenanceExclusion_PublicToPrivate(in *ControlPlaneMaintenanceExclusion, out *privatev1.ControlPlaneMaintenanceExclusion, s conversion.Scope) error {
	return autoConvert_ControlPlaneMaintenanceExclusion_PublicToPrivate(in, out, s)
}

func autoConvert_ControlPlaneMaintenanceRecurrence_PrivateToPublic(in *privatev1.ControlPlaneMaintenanceRecurrence, out *ControlPlaneMaintenanceRecurrence, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneMaintenanceRecurrence_PrivateToPublic is an autogenerated conversion function.
func Convert_ControlPlaneMaintenanceRecurrence_PrivateToPublic(in *privatev1.ControlPlaneMaintenanceRecurrence, out *ControlPlaneMaintenanceRecurrence, s conversion.Scope) error {
	return autoConvert_ControlPlaneMaintenanceRecurrence_PrivateToPublic(in, out, s)
}

func autoConvert_ControlPlaneMaintenanceRecurrence_PublicToPrivate(in *ControlPlaneMaintenanceRecurrence, out *privatev1.ControlPlaneMaintenanceRecurrence, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneMaintenanceRecurrence_PublicToPrivate is an autogenerated conversion function.
func Convert_ControlPlaneMaintenanceRecurrence_PublicToPrivate(in *ControlPlaneMaintenanceRecurrence, out *privatev1.ControlPlaneMaintenanceRecurrence, s conversion.Scope) error {
	return autoConvert_ControlPlaneMaintenanceRecurrence_PublicToPrivate(in, out, s)
}

func autoConvert_ControlPlaneMaintenanceWindow_PrivateToPublic(in *privatev1.ControlPlaneMaintenanceWindow, out *ControlPlaneMaintenanceWindow, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneMaintenanceWindow_PrivateToPublic is an autogenerated conversion function.
func Convert_ControlPlaneMaintenanceWindow_PrivateToPublic(in *privatev1.ControlPlaneMaintenanceWindow, out *ControlPlaneMaintenanceWindow, s conversion.Scope) error {
	return autoConvert_ControlPlaneMaintenanceWindow_PrivateToPublic(in, out, s)
}

func autoConvert_ControlPlaneMaintenanceWindow_PublicToPrivate(in *ControlPlaneMaintenanceWindow, out *privatev1.ControlPlaneMaintenanceWindow, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneMaintenanceWindow_PublicToPrivate is an autogenerated conversion function.
func Convert_ControlPlaneMaintenanceWindow_PublicToPrivate(in *ControlPlaneMaintenanceWindow, out *privatev1.ControlPlaneMaintenanceWindow, s conversion.Scope) error {
	return autoConvert_ControlPlaneMaintenanceWindow_PublicToPrivate(in, out, s)
}

func autoConvert_ControlPlaneUpgradePolicy_PrivateToPublic(in *privatev1.ControlPlaneUpgradePolicy, out *ControlPlaneUpgradePolicy, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneUpgradePolicy_PrivateToPublic is an autogenerated conversion function.
func Convert_ControlPlaneUpgradePolicy_PrivateToPublic(in *privatev1.ControlPlaneUpgradePolicy, out *ControlPlaneUpgradePolicy, s conversion.Scope) error {
	return autoConvert_ControlPlaneUpgradePolicy_PrivateToPublic(in, out, s)
}

func autoConvert_ControlPlaneUpgradePolicy_PublicToPrivate(in *ControlPlaneUpgradePolicy, out *privatev1.ControlPlaneUpgradePolicy, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneUpgradePolicy_PublicToPrivate is an autogenerated conversion function.
func Convert_ControlPlaneUpgradePolicy_PublicToPrivate(in *ControlPlaneUpgradePolicy, out *privatev1.ControlPlaneUpgradePolicy, s conversion.Scope) error {
	return autoConvert_ControlPlaneUpgradePolicy_PublicToPrivate(in, out, s)
}

func autoConvert_ControlPlaneUpgradePolicyList_PrivateToPublic(in *privatev1.ControlPlaneUpgradePolicyList, out *ControlPlaneUpgradePolicyList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneUpgradePolicyList_PrivateToPublic is an autogenerated conversion function.
func Convert_ControlPlaneUpgradePolicyList_PrivateToPublic(in *privatev1.ControlPlaneUpgradePolicyList, out *ControlPlaneUpgradePolicyList, s conversion.Scope) error {
	return autoConvert_ControlPlaneUpgradePolicyList_PrivateToPublic(in, out, s)
}

func autoConvert_ControlPlaneUpgradePolicyList_PublicToPrivate(in *ControlPlaneUpgradePolicyList, out *privatev1.ControlPlaneUpgradePolicyList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneUpgradePolicyList_PublicToPrivate is an autogenerated conversion function.
func Convert_ControlPlaneUpgradePolicyList_PublicToPrivate(in *ControlPlaneUpgradePolicyList, out *privatev1.ControlPlaneUpgradePolicyList, s conversion.Scope) error {
	return autoConvert_ControlPlaneUpgradePolicyList_PublicToPrivate(in, out, s)
}

func autoConvert_ControlPlaneUpgradePolicySpec_PrivateToPublic(in *privatev1.ControlPlaneUpgradePolicySpec, out *ControlPlaneUpgradePolicySpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneUpgradePolicySpec_PrivateToPublic is an autogenerated conversion function.
func Convert_ControlPlaneUpgradePolicySpec_PrivateToPublic(in *privatev1.ControlPlaneUpgradePolicySpec, out *ControlPlaneUpgradePolicySpec, s conversion.Scope) error {
	return autoConvert_ControlPlaneUpgradePolicySpec_PrivateToPublic(in, out, s)
}

func autoConvert_ControlPlaneUpgradePolicySpec_PublicToPrivate(in *ControlPlaneUpgradePolicySpec, out *privatev1.ControlPlaneUpgradePolicySpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneUpgradePolicySpec_PublicToPrivate is an autogenerated conversion function.
func Convert_ControlPlaneUpgradePolicySpec_PublicToPrivate(in *ControlPlaneUpgradePolicySpec, out *privatev1.ControlPlaneUpgradePolicySpec, s conversion.Scope) error {
	return autoConvert_ControlPlaneUpgradePolicySpec_PublicToPrivate(in, out, s)
}

func autoConvert_ControlPlaneUpgradePolicyStatus_PrivateToPublic(in *privatev1.ControlPlaneUpgradePolicyStatus, out *ControlPlaneUpgradePolicyStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneUpgradePolicyStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_ControlPlaneUpgradePolicyStatus_PrivateToPublic(in *privatev1.ControlPlaneUpgradePolicyStatus, out *ControlPlaneUpgradePolicyStatus, s conversion.Scope) error {
	return autoConvert_ControlPlaneUpgradePolicyStatus_PrivateToPublic(in, out, s)
}

func autoConvert_ControlPlaneUpgradePolicyStatus_PublicToPrivate(in *ControlPlaneUpgradePolicyStatus, out *privatev1.ControlPlaneUpgradePolicyStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ControlPlaneUpgradePolicyStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_ControlPlaneUpgradePolicyStatus_PublicToPrivate(in *ControlPlaneUpgradePolicyStatus, out *privatev1.ControlPlaneUpgradePolicyStatus, s conversion.Scope) error {
	return autoConvert_ControlPlaneUpgradePolicyStatus_PublicToPrivate(in, out, s)
}

func autoConvert_DNSSpec_PrivateToPublic(in *privatev1.DNSSpec, out *DNSSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_DNSSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_DNSSpec_PrivateToPublic(in *privatev1.DNSSpec, out *DNSSpec, s conversion.Scope) error {
	return autoConvert_DNSSpec_PrivateToPublic(in, out, s)
}

func autoConvert_DNSSpec_PublicToPrivate(in *DNSSpec, out *privatev1.DNSSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_DNSSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_DNSSpec_PublicToPrivate(in *DNSSpec, out *privatev1.DNSSpec, s conversion.Scope) error {
	return autoConvert_DNSSpec_PublicToPrivate(in, out, s)
}

func autoConvert_GCPClusterPlatform_PrivateToPublic(in *privatev1.GCPClusterPlatform, out *GCPClusterPlatform, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPClusterPlatform_PrivateToPublic is an autogenerated conversion function.
func Convert_GCPClusterPlatform_PrivateToPublic(in *privatev1.GCPClusterPlatform, out *GCPClusterPlatform, s conversion.Scope) error {
	return autoConvert_GCPClusterPlatform_PrivateToPublic(in, out, s)
}

func autoConvert_GCPClusterPlatform_PublicToPrivate(in *GCPClusterPlatform, out *privatev1.GCPClusterPlatform, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPClusterPlatform_PublicToPrivate is an autogenerated conversion function.
func Convert_GCPClusterPlatform_PublicToPrivate(in *GCPClusterPlatform, out *privatev1.GCPClusterPlatform, s conversion.Scope) error {
	return autoConvert_GCPClusterPlatform_PublicToPrivate(in, out, s)
}

func autoConvert_GCPNodePoolPlatform_PrivateToPublic(in *privatev1.GCPNodePoolPlatform, out *GCPNodePoolPlatform, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPNodePoolPlatform_PrivateToPublic is an autogenerated conversion function.
func Convert_GCPNodePoolPlatform_PrivateToPublic(in *privatev1.GCPNodePoolPlatform, out *GCPNodePoolPlatform, s conversion.Scope) error {
	return autoConvert_GCPNodePoolPlatform_PrivateToPublic(in, out, s)
}

func autoConvert_GCPNodePoolPlatform_PublicToPrivate(in *GCPNodePoolPlatform, out *privatev1.GCPNodePoolPlatform, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPNodePoolPlatform_PublicToPrivate is an autogenerated conversion function.
func Convert_GCPNodePoolPlatform_PublicToPrivate(in *GCPNodePoolPlatform, out *privatev1.GCPNodePoolPlatform, s conversion.Scope) error {
	return autoConvert_GCPNodePoolPlatform_PublicToPrivate(in, out, s)
}

func autoConvert_GCPResourceLabel_PrivateToPublic(in *privatev1.GCPResourceLabel, out *GCPResourceLabel, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPResourceLabel_PrivateToPublic is an autogenerated conversion function.
func Convert_GCPResourceLabel_PrivateToPublic(in *privatev1.GCPResourceLabel, out *GCPResourceLabel, s conversion.Scope) error {
	return autoConvert_GCPResourceLabel_PrivateToPublic(in, out, s)
}

func autoConvert_GCPResourceLabel_PublicToPrivate(in *GCPResourceLabel, out *privatev1.GCPResourceLabel, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_GCPResourceLabel_PublicToPrivate is an autogenerated conversion function.
func Convert_GCPResourceLabel_PublicToPrivate(in *GCPResourceLabel, out *privatev1.GCPResourceLabel, s conversion.Scope) error {
	return autoConvert_GCPResourceLabel_PublicToPrivate(in, out, s)
}

func autoConvert_HostedClusterResult_PrivateToPublic(in *privatev1.HostedClusterResult, out *HostedClusterResult, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_HostedClusterResult_PrivateToPublic is an autogenerated conversion function.
func Convert_HostedClusterResult_PrivateToPublic(in *privatev1.HostedClusterResult, out *HostedClusterResult, s conversion.Scope) error {
	return autoConvert_HostedClusterResult_PrivateToPublic(in, out, s)
}

func autoConvert_HostedClusterResult_PublicToPrivate(in *HostedClusterResult, out *privatev1.HostedClusterResult, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_HostedClusterResult_PublicToPrivate is an autogenerated conversion function.
func Convert_HostedClusterResult_PublicToPrivate(in *HostedClusterResult, out *privatev1.HostedClusterResult, s conversion.Scope) error {
	return autoConvert_HostedClusterResult_PublicToPrivate(in, out, s)
}

func autoConvert_MachineNetworkEntry_PrivateToPublic(in *privatev1.MachineNetworkEntry, out *MachineNetworkEntry, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_MachineNetworkEntry_PrivateToPublic is an autogenerated conversion function.
func Convert_MachineNetworkEntry_PrivateToPublic(in *privatev1.MachineNetworkEntry, out *MachineNetworkEntry, s conversion.Scope) error {
	return autoConvert_MachineNetworkEntry_PrivateToPublic(in, out, s)
}

func autoConvert_MachineNetworkEntry_PublicToPrivate(in *MachineNetworkEntry, out *privatev1.MachineNetworkEntry, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_MachineNetworkEntry_PublicToPrivate is an autogenerated conversion function.
func Convert_MachineNetworkEntry_PublicToPrivate(in *MachineNetworkEntry, out *privatev1.MachineNetworkEntry, s conversion.Scope) error {
	return autoConvert_MachineNetworkEntry_PublicToPrivate(in, out, s)
}

func autoConvert_NetworkingSpec_PrivateToPublic(in *privatev1.NetworkingSpec, out *NetworkingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NetworkingSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_NetworkingSpec_PrivateToPublic(in *privatev1.NetworkingSpec, out *NetworkingSpec, s conversion.Scope) error {
	return autoConvert_NetworkingSpec_PrivateToPublic(in, out, s)
}

func autoConvert_NetworkingSpec_PublicToPrivate(in *NetworkingSpec, out *privatev1.NetworkingSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NetworkingSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_NetworkingSpec_PublicToPrivate(in *NetworkingSpec, out *privatev1.NetworkingSpec, s conversion.Scope) error {
	return autoConvert_NetworkingSpec_PublicToPrivate(in, out, s)
}

func autoConvert_NodePool_PrivateToPublic(in *privatev1.NodePool, out *NodePool, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePool_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePool_PrivateToPublic(in *privatev1.NodePool, out *NodePool, s conversion.Scope) error {
	return autoConvert_NodePool_PrivateToPublic(in, out, s)
}

func autoConvert_NodePool_PublicToPrivate(in *NodePool, out *privatev1.NodePool, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePool_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePool_PublicToPrivate(in *NodePool, out *privatev1.NodePool, s conversion.Scope) error {
	return autoConvert_NodePool_PublicToPrivate(in, out, s)
}

func autoConvert_NodePoolList_PrivateToPublic(in *privatev1.NodePoolList, out *NodePoolList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolList_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePoolList_PrivateToPublic(in *privatev1.NodePoolList, out *NodePoolList, s conversion.Scope) error {
	return autoConvert_NodePoolList_PrivateToPublic(in, out, s)
}

func autoConvert_NodePoolList_PublicToPrivate(in *NodePoolList, out *privatev1.NodePoolList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolList_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePoolList_PublicToPrivate(in *NodePoolList, out *privatev1.NodePoolList, s conversion.Scope) error {
	return autoConvert_NodePoolList_PublicToPrivate(in, out, s)
}

func autoConvert_NodePoolPlatformSpec_PrivateToPublic(in *privatev1.NodePoolPlatformSpec, out *NodePoolPlatformSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolPlatformSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePoolPlatformSpec_PrivateToPublic(in *privatev1.NodePoolPlatformSpec, out *NodePoolPlatformSpec, s conversion.Scope) error {
	return autoConvert_NodePoolPlatformSpec_PrivateToPublic(in, out, s)
}

func autoConvert_NodePoolPlatformSpec_PublicToPrivate(in *NodePoolPlatformSpec, out *privatev1.NodePoolPlatformSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolPlatformSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePoolPlatformSpec_PublicToPrivate(in *NodePoolPlatformSpec, out *privatev1.NodePoolPlatformSpec, s conversion.Scope) error {
	return autoConvert_NodePoolPlatformSpec_PublicToPrivate(in, out, s)
}

func autoConvert_NodePoolSpec_PrivateToPublic(in *privatev1.NodePoolSpec, out *NodePoolSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePoolSpec_PrivateToPublic(in *privatev1.NodePoolSpec, out *NodePoolSpec, s conversion.Scope) error {
	return autoConvert_NodePoolSpec_PrivateToPublic(in, out, s)
}

func autoConvert_NodePoolSpec_PublicToPrivate(in *NodePoolSpec, out *privatev1.NodePoolSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePoolSpec_PublicToPrivate(in *NodePoolSpec, out *privatev1.NodePoolSpec, s conversion.Scope) error {
	return autoConvert_NodePoolSpec_PublicToPrivate(in, out, s)
}

func autoConvert_NodePoolStatus_PrivateToPublic(in *privatev1.NodePoolStatus, out *NodePoolStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_NodePoolStatus_PrivateToPublic(in *privatev1.NodePoolStatus, out *NodePoolStatus, s conversion.Scope) error {
	return autoConvert_NodePoolStatus_PrivateToPublic(in, out, s)
}

func autoConvert_NodePoolStatus_PublicToPrivate(in *NodePoolStatus, out *privatev1.NodePoolStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_NodePoolStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_NodePoolStatus_PublicToPrivate(in *NodePoolStatus, out *privatev1.NodePoolStatus, s conversion.Scope) error {
	return autoConvert_NodePoolStatus_PublicToPrivate(in, out, s)
}

func autoConvert_Quota_PrivateToPublic(in *privatev1.Quota, out *Quota, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Quota_PrivateToPublic is an autogenerated conversion function.
func Convert_Quota_PrivateToPublic(in *privatev1.Quota, out *Quota, s conversion.Scope) error {
	return autoConvert_Quota_PrivateToPublic(in, out, s)
}

func autoConvert_Quota_PublicToPrivate(in *Quota, out *privatev1.Quota, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Quota_PublicToPrivate is an autogenerated conversion function.
func Convert_Quota_PublicToPrivate(in *Quota, out *privatev1.Quota, s conversion.Scope) error {
	return autoConvert_Quota_PublicToPrivate(in, out, s)
}

func autoConvert_QuotaList_PrivateToPublic(in *privatev1.QuotaList, out *QuotaList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaList_PrivateToPublic is an autogenerated conversion function.
func Convert_QuotaList_PrivateToPublic(in *privatev1.QuotaList, out *QuotaList, s conversion.Scope) error {
	return autoConvert_QuotaList_PrivateToPublic(in, out, s)
}

func autoConvert_QuotaList_PublicToPrivate(in *QuotaList, out *privatev1.QuotaList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaList_PublicToPrivate is an autogenerated conversion function.
func Convert_QuotaList_PublicToPrivate(in *QuotaList, out *privatev1.QuotaList, s conversion.Scope) error {
	return autoConvert_QuotaList_PublicToPrivate(in, out, s)
}

func autoConvert_QuotaRequest_PrivateToPublic(in *privatev1.QuotaRequest, out *QuotaRequest, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaRequest_PrivateToPublic is an autogenerated conversion function.
func Convert_QuotaRequest_PrivateToPublic(in *privatev1.QuotaRequest, out *QuotaRequest, s conversion.Scope) error {
	return autoConvert_QuotaRequest_PrivateToPublic(in, out, s)
}

func autoConvert_QuotaRequest_PublicToPrivate(in *QuotaRequest, out *privatev1.QuotaRequest, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaRequest_PublicToPrivate is an autogenerated conversion function.
func Convert_QuotaRequest_PublicToPrivate(in *QuotaRequest, out *privatev1.QuotaRequest, s conversion.Scope) error {
	return autoConvert_QuotaRequest_PublicToPrivate(in, out, s)
}

func autoConvert_QuotaRequestList_PrivateToPublic(in *privatev1.QuotaRequestList, out *QuotaRequestList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaRequestList_PrivateToPublic is an autogenerated conversion function.
func Convert_QuotaRequestList_PrivateToPublic(in *privatev1.QuotaRequestList, out *QuotaRequestList, s conversion.Scope) error {
	return autoConvert_QuotaRequestList_PrivateToPublic(in, out, s)
}

func autoConvert_QuotaRequestList_PublicToPrivate(in *QuotaRequestList, out *privatev1.QuotaRequestList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaRequestList_PublicToPrivate is an autogenerated conversion function.
func Convert_QuotaRequestList_PublicToPrivate(in *QuotaRequestList, out *privatev1.QuotaRequestList, s conversion.Scope) error {
	return autoConvert_QuotaRequestList_PublicToPrivate(in, out, s)
}

func autoConvert_QuotaRequestSpec_PrivateToPublic(in *privatev1.QuotaRequestSpec, out *QuotaRequestSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaRequestSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_QuotaRequestSpec_PrivateToPublic(in *privatev1.QuotaRequestSpec, out *QuotaRequestSpec, s conversion.Scope) error {
	return autoConvert_QuotaRequestSpec_PrivateToPublic(in, out, s)
}

func autoConvert_QuotaRequestSpec_PublicToPrivate(in *QuotaRequestSpec, out *privatev1.QuotaRequestSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaRequestSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_QuotaRequestSpec_PublicToPrivate(in *QuotaRequestSpec, out *privatev1.QuotaRequestSpec, s conversion.Scope) error {
	return autoConvert_QuotaRequestSpec_PublicToPrivate(in, out, s)
}

func autoConvert_QuotaRequestStatus_PrivateToPublic(in *privatev1.QuotaRequestStatus, out *QuotaRequestStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaRequestStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_QuotaRequestStatus_PrivateToPublic(in *privatev1.QuotaRequestStatus, out *QuotaRequestStatus, s conversion.Scope) error {
	return autoConvert_QuotaRequestStatus_PrivateToPublic(in, out, s)
}

func autoConvert_QuotaRequestStatus_PublicToPrivate(in *QuotaRequestStatus, out *privatev1.QuotaRequestStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaRequestStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_QuotaRequestStatus_PublicToPrivate(in *QuotaRequestStatus, out *privatev1.QuotaRequestStatus, s conversion.Scope) error {
	return autoConvert_QuotaRequestStatus_PublicToPrivate(in, out, s)
}

func autoConvert_QuotaResourceSpec_PrivateToPublic(in *privatev1.QuotaResourceSpec, out *QuotaResourceSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaResourceSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_QuotaResourceSpec_PrivateToPublic(in *privatev1.QuotaResourceSpec, out *QuotaResourceSpec, s conversion.Scope) error {
	return autoConvert_QuotaResourceSpec_PrivateToPublic(in, out, s)
}

func autoConvert_QuotaResourceSpec_PublicToPrivate(in *QuotaResourceSpec, out *privatev1.QuotaResourceSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaResourceSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_QuotaResourceSpec_PublicToPrivate(in *QuotaResourceSpec, out *privatev1.QuotaResourceSpec, s conversion.Scope) error {
	return autoConvert_QuotaResourceSpec_PublicToPrivate(in, out, s)
}

func autoConvert_QuotaResourceStatus_PrivateToPublic(in *privatev1.QuotaResourceStatus, out *QuotaResourceStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaResourceStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_QuotaResourceStatus_PrivateToPublic(in *privatev1.QuotaResourceStatus, out *QuotaResourceStatus, s conversion.Scope) error {
	return autoConvert_QuotaResourceStatus_PrivateToPublic(in, out, s)
}

func autoConvert_QuotaResourceStatus_PublicToPrivate(in *QuotaResourceStatus, out *privatev1.QuotaResourceStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaResourceStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_QuotaResourceStatus_PublicToPrivate(in *QuotaResourceStatus, out *privatev1.QuotaResourceStatus, s conversion.Scope) error {
	return autoConvert_QuotaResourceStatus_PublicToPrivate(in, out, s)
}

func autoConvert_QuotaSpec_PrivateToPublic(in *privatev1.QuotaSpec, out *QuotaSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_QuotaSpec_PrivateToPublic(in *privatev1.QuotaSpec, out *QuotaSpec, s conversion.Scope) error {
	return autoConvert_QuotaSpec_PrivateToPublic(in, out, s)
}

func autoConvert_QuotaSpec_PublicToPrivate(in *QuotaSpec, out *privatev1.QuotaSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_QuotaSpec_PublicToPrivate(in *QuotaSpec, out *privatev1.QuotaSpec, s conversion.Scope) error {
	return autoConvert_QuotaSpec_PublicToPrivate(in, out, s)
}

func autoConvert_QuotaStatus_PrivateToPublic(in *privatev1.QuotaStatus, out *QuotaStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaStatus_PrivateToPublic is an autogenerated conversion function.
func Convert_QuotaStatus_PrivateToPublic(in *privatev1.QuotaStatus, out *QuotaStatus, s conversion.Scope) error {
	return autoConvert_QuotaStatus_PrivateToPublic(in, out, s)
}

func autoConvert_QuotaStatus_PublicToPrivate(in *QuotaStatus, out *privatev1.QuotaStatus, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_QuotaStatus_PublicToPrivate is an autogenerated conversion function.
func Convert_QuotaStatus_PublicToPrivate(in *QuotaStatus, out *privatev1.QuotaStatus, s conversion.Scope) error {
	return autoConvert_QuotaStatus_PublicToPrivate(in, out, s)
}

func autoConvert_ReleaseSpec_PrivateToPublic(in *privatev1.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ReleaseSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_ReleaseSpec_PrivateToPublic(in *privatev1.ReleaseSpec, out *ReleaseSpec, s conversion.Scope) error {
	return autoConvert_ReleaseSpec_PrivateToPublic(in, out, s)
}

func autoConvert_ReleaseSpec_PublicToPrivate(in *ReleaseSpec, out *privatev1.ReleaseSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ReleaseSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_ReleaseSpec_PublicToPrivate(in *ReleaseSpec, out *privatev1.ReleaseSpec, s conversion.Scope) error {
	return autoConvert_ReleaseSpec_PublicToPrivate(in, out, s)
}

func autoConvert_ServiceAccountsRef_PrivateToPublic(in *privatev1.ServiceAccountsRef, out *ServiceAccountsRef, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ServiceAccountsRef_PrivateToPublic is an autogenerated conversion function.
func Convert_ServiceAccountsRef_PrivateToPublic(in *privatev1.ServiceAccountsRef, out *ServiceAccountsRef, s conversion.Scope) error {
	return autoConvert_ServiceAccountsRef_PrivateToPublic(in, out, s)
}

func autoConvert_ServiceAccountsRef_PublicToPrivate(in *ServiceAccountsRef, out *privatev1.ServiceAccountsRef, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_ServiceAccountsRef_PublicToPrivate is an autogenerated conversion function.
func Convert_ServiceAccountsRef_PublicToPrivate(in *ServiceAccountsRef, out *privatev1.ServiceAccountsRef, s conversion.Scope) error {
	return autoConvert_ServiceAccountsRef_PublicToPrivate(in, out, s)
}

func autoConvert_TaintSpec_PrivateToPublic(in *privatev1.TaintSpec, out *TaintSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_TaintSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_TaintSpec_PrivateToPublic(in *privatev1.TaintSpec, out *TaintSpec, s conversion.Scope) error {
	return autoConvert_TaintSpec_PrivateToPublic(in, out, s)
}

func autoConvert_TaintSpec_PublicToPrivate(in *TaintSpec, out *privatev1.TaintSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_TaintSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_TaintSpec_PublicToPrivate(in *TaintSpec, out *privatev1.TaintSpec, s conversion.Scope) error {
	return autoConvert_TaintSpec_PublicToPrivate(in, out, s)
}

func autoConvert_Version_PrivateToPublic(in *privatev1.Version, out *Version, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Version_PrivateToPublic is an autogenerated conversion function.
func Convert_Version_PrivateToPublic(in *privatev1.Version, out *Version, s conversion.Scope) error {
	return autoConvert_Version_PrivateToPublic(in, out, s)
}

func autoConvert_Version_PublicToPrivate(in *Version, out *privatev1.Version, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_Version_PublicToPrivate is an autogenerated conversion function.
func Convert_Version_PublicToPrivate(in *Version, out *privatev1.Version, s conversion.Scope) error {
	return autoConvert_Version_PublicToPrivate(in, out, s)
}

func autoConvert_VersionList_PrivateToPublic(in *privatev1.VersionList, out *VersionList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_VersionList_PrivateToPublic is an autogenerated conversion function.
func Convert_VersionList_PrivateToPublic(in *privatev1.VersionList, out *VersionList, s conversion.Scope) error {
	return autoConvert_VersionList_PrivateToPublic(in, out, s)
}

func autoConvert_VersionList_PublicToPrivate(in *VersionList, out *privatev1.VersionList, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_VersionList_PublicToPrivate is an autogenerated conversion function.
func Convert_VersionList_PublicToPrivate(in *VersionList, out *privatev1.VersionList, s conversion.Scope) error {
	return autoConvert_VersionList_PublicToPrivate(in, out, s)
}

func autoConvert_VersionSpec_PrivateToPublic(in *privatev1.VersionSpec, out *VersionSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_VersionSpec_PrivateToPublic is an autogenerated conversion function.
func Convert_VersionSpec_PrivateToPublic(in *privatev1.VersionSpec, out *VersionSpec, s conversion.Scope) error {
	return autoConvert_VersionSpec_PrivateToPublic(in, out, s)
}

func autoConvert_VersionSpec_PublicToPrivate(in *VersionSpec, out *privatev1.VersionSpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_VersionSpec_PublicToPrivate is an autogenerated conversion function.
func Convert_VersionSpec_PublicToPrivate(in *VersionSpec, out *privatev1.VersionSpec, s conversion.Scope) error {
	return autoConvert_VersionSpec_PublicToPrivate(in, out, s)
}

func autoConvert_WorkloadIdentitySpec_PrivateToPublic(in *privatev1.WorkloadIdentitySpec, out *WorkloadIdentitySpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_WorkloadIdentitySpec_PrivateToPublic is an autogenerated conversion function.
func Convert_WorkloadIdentitySpec_PrivateToPublic(in *privatev1.WorkloadIdentitySpec, out *WorkloadIdentitySpec, s conversion.Scope) error {
	return autoConvert_WorkloadIdentitySpec_PrivateToPublic(in, out, s)
}

func autoConvert_WorkloadIdentitySpec_PublicToPrivate(in *WorkloadIdentitySpec, out *privatev1.WorkloadIdentitySpec, s conversion.Scope) error {
	data, err := json.Marshal(in)
	if err != nil {
		return err
	}
	return json.Unmarshal(data, out)
}

// Convert_WorkloadIdentitySpec_PublicToPrivate is an autogenerated conversion function.
func Convert_WorkloadIdentitySpec_PublicToPrivate(in *WorkloadIdentitySpec, out *privatev1.WorkloadIdentitySpec, s conversion.Scope) error {
	return autoConvert_WorkloadIdentitySpec_PublicToPrivate(in, out, s)
}
